/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.36
 * Generated at: 2026-08-24 13:32:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.snpp.crmparaguay.model.Cliente;
import java.util.List;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.snpp.crmparaguay.model.Cliente");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"es\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>CRMParaguay</title>\r\n");
      out.write("    <!-- Tailwind CSS CDN -->\r\n");
      out.write("    <script src=\"https://cdn.tailwindcss.com\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"bg-gray-50 text-gray-800 antialiased\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Contenedor Principal -->\r\n");
      out.write("    <div class=\"max-w-7xl mx-auto px-4 py-8\">\r\n");
      out.write("        \r\n");
      out.write("        <!-- Encabezado -->\r\n");
      out.write("        <header class=\"mb-8\">\r\n");
      out.write("            <h1 class=\"text-3xl font-extrabold text-blue-600\">CRMParaguay</h1>\r\n");
      out.write("            <p class=\"text-sm text-gray-500\">Sistema de Gestión de Clientes</p>\r\n");
      out.write("        </header>\r\n");
      out.write("\r\n");
      out.write("        <!-- Layout de dos columnas: Formulario y Tabla -->\r\n");
      out.write("        <div class=\"grid grid-cols-1 lg:grid-cols-3 gap-8\">\r\n");
      out.write("            \r\n");
      out.write("            <!-- Columna Izquierda: Formulario -->\r\n");
      out.write("            <div class=\"bg-white p-6 rounded-xl shadow-sm border border-gray-100 h-fit\">\r\n");
      out.write("                <h2 class=\"text-xl font-bold text-gray-700 mb-4 pb-2 border-b border-gray-100\">\r\n");
      out.write("                ");

                    Cliente clienteEditar = (Cliente) request.getAttribute("clienteEditar");
                    if (clienteEditar != null) {
                        out.print("Editar Cliente");
                    } else {
                        out.print("Nuevo Cliente");
                    }
                
      out.write("\r\n");
      out.write("                </h2>\r\n");
      out.write("\r\n");
      out.write("                <form action=\"ClienteServlet\" method=\"post\" class=\"space-y-4\">\r\n");
      out.write("\r\n");
      out.write("                    ");

                        if (clienteEditar != null) {
                            out.print("<input type='hidden' name='idCliente' value='" + clienteEditar.getIdCliente() + "'>");
                        }
                    
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    <div>\r\n");
      out.write("                        <label class=\"block text-sm font-medium text-gray-600 mb-1\">Nombre:</label>\r\n");
      out.write("                        <input type=\"text\" name=\"nombre\"\r\n");
      out.write("                               value=\"");
      out.print( (clienteEditar != null) ? clienteEditar.getNombre() : "" );
      out.write("\" \r\n");
      out.write("                               class=\"w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent text-sm\" required>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div>\r\n");
      out.write("                        <label class=\"block text-sm font-medium text-gray-600 mb-1\">Email:</label>\r\n");
      out.write("                        <input type=\"email\" name=\"email\"\r\n");
      out.write("                               value=\"");
      out.print( (clienteEditar != null) ? clienteEditar.getEmail() : "" );
      out.write("\" \r\n");
      out.write("                               class=\"w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent text-sm\" required>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div>\r\n");
      out.write("                        <label class=\"block text-sm font-medium text-gray-600 mb-1\">Teléfono:</label>\r\n");
      out.write("                        <input type=\"text\" name=\"telefono\"\r\n");
      out.write("                               value=\"");
      out.print( (clienteEditar != null) ? clienteEditar.getTelefono() : "" );
      out.write("\"\r\n");
      out.write("                               class=\"w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent text-sm\">\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div>\r\n");
      out.write("                        <label class=\"block text-sm font-medium text-gray-600 mb-1\">Empresa:</label>\r\n");
      out.write("                        <input type=\"text\" name=\"empresa\"\r\n");
      out.write("                               value=\"");
      out.print( (clienteEditar != null) ? clienteEditar.getEmpresa() : "" );
      out.write("\"\r\n");
      out.write("                               class=\"w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent text-sm\">\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <button type=\"submit\" class=\"w-full bg-blue-600 hover:bg-blue-700 text-white font-medium py-2 px-4 rounded-lg transition duration-200 text-sm shadow-sm\">\r\n");
      out.write("                        Guardar\r\n");
      out.write("                    </button>\r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Columna Derecha: Tabla -->\r\n");
      out.write("            <div class=\"lg:col-span-2 bg-white p-6 rounded-xl shadow-sm border border-gray-100\">\r\n");
      out.write("                <h3 class=\"text-xl font-bold text-gray-700 mb-4 pb-2 border-b border-gray-100\">Lista de Clientes</h3>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"overflow-x-auto\">\r\n");
      out.write("                    <table class=\"w-full text-left border-collapse\">\r\n");
      out.write("                        <thead>\r\n");
      out.write("                            <tr class=\"bg-gray-50 text-gray-600 text-xs uppercase tracking-wider border-b border-gray-200\">\r\n");
      out.write("                                <th class=\"py-3 px-3\">ID</th>\r\n");
      out.write("                                <th class=\"py-3 px-3\">Nombre</th>\r\n");
      out.write("                                <th class=\"py-3 px-3\">Email</th>\r\n");
      out.write("                                <th class=\"py-3 px-3\">Teléfono</th>\r\n");
      out.write("                                <th class=\"py-3 px-3\">Empresa</th>\r\n");
      out.write("                                <th class=\"py-3 px-3\">Fecha registro</th>\r\n");
      out.write("                                <th class=\"py-3 px-3 text-center\">Acciones</th>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                        </thead>\r\n");
      out.write("                        <tbody class=\"divide-y divide-gray-100 text-sm text-gray-600\">\r\n");
      out.write("                            ");

                                List<Cliente> listaClientes = (List<Cliente>) request.getAttribute("listaClientes");
                                if (listaClientes != null) {
                                    for (Cliente c : listaClientes) {
                                        out.println("<tr class='hover:bg-gray-50'>");
                                        out.println("<td class='py-3 px-3 font-medium text-gray-900'>" + c.getIdCliente() + "</td>");
                                        out.println("<td class='py-3 px-3'>" + c.getNombre() + "</td>");
                                        out.println("<td class='py-3 px-3'>" + c.getEmail() + "</td>");
                                        out.println("<td class='py-3 px-3'>" + c.getTelefono() + "</td>");
                                        out.println("<td class='py-3 px-3'>" + c.getEmpresa() + "</td>");
                                        out.println("<td class='py-3 px-3 text-xs text-gray-400'>" + c.getFechaRegistro() + "</td>");
                                        out.println("<td class='py-3 px-3 text-center space-x-2'>" +
                                            "<a href='ClienteServlet?accion=editar&id=" + c.getIdCliente() + "' class='inline-block bg-amber-500 hover:bg-amber-600 text-white text-xs px-2.5 py-1.5 rounded transition'>Editar</a>" +
                                            "<a href='ClienteServlet?accion=eliminar&id=" + c.getIdCliente() + "' class='inline-block bg-red-500 hover:bg-red-600 text-white text-xs px-2.5 py-1.5 rounded transition' onclick='return confirm(\"¿Estás seguro?\")'>Eliminar</a>" +
                                            "</td>");
                                        out.println("</tr>");
                                    }
                                }
                            
      out.write("\r\n");
      out.write("                        </tbody>\r\n");
      out.write("                    </table>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
